### ISSUE TITLE
[Mask_RCNN] No module named 'pycocotools'

### ISSUE THREAD

**Issue by alicest9** [roboticslab-uc3m/installation-guides#63]
Running [Mask_RCNN](https://github.com/matterport/Mask_RCNN):
```bash
python3 coco.py train --dataset=/path/to/coco/ --model=coco
```

Results in:
```
Traceback (most recent call last):
  File "coco.py", line 42, in <module>
    from pycocotools.coco import COCO
ImportError: No module named 'pycocotools'
```

**Comment by alicest9** [comment]
BTW, duplicate of https://github.com/matterport/Mask_RCNN/issues/6

**Comment by alicest9** [comment]
Trying https://github.com/matterport/Mask_RCNN/issues/6#issuecomment-341623963 (has 73 :+1:) `master` at https://github.com/matterport/Mask_RCNN/tree/b29b32c7e402254595ae6819cd9ebaa0ddddde8e
Running:
```
make
```

Results in:
```
python setup.py build_ext --inplace
running build_ext
building 'pycocotools._mask' extension
creating build
creating build/common
creating build/temp.linux-x86_64-2.7
creating build/temp.linux-x86_64-2.7/pycocotools
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/usr/local/lib/python2.7/dist-packages/numpy/core/include -I../common -I/usr/include/python2.7 -c ../common/maskApi.c -o build/temp.linux-x86_64-2.7/../common/maskApi.o -Wno-cpp -Wno-unused-function -std=c99
^[^@../common/maskApi.c: In function ‘rleToBbox’:
../common/maskApi.c:141:31: warning: ‘xp’ may be used uninitialized in this function [-Wmaybe-uninitialized]
       if(j%2==0) xp=x; else if(xp<x) { ys=0; ye=h-1; }
                               ^
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/usr/local/lib/python2.7/dist-packages/numpy/core/include -I../common -I/usr/include/python2.7 -c pycocotools/_mask.c -o build/temp.linux-x86_64-2.7/pycocotools/_mask.o -Wno-cpp -Wno-unused-function -std=c99
x86_64-linux-gnu-gcc: error: pycocotools/_mask.c: No such file or directory
x86_64-linux-gnu-gcc: fatal error: no input files
compilation terminated.
error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
Makefile:3: recipe for target 'all' failed
make: *** [all] Error 1
```

**Comment by alicest9** [comment]
https://github.com/matterport/Mask_RCNN/issues/6#issuecomment-371727392 looks better, running:
```bash
pip install "git+https://github.com/philferriere/cocoapi.git#egg=pycocotools&subdirectory=PythonAPI"
```

Results in:
```
Collecting pycocotools from git+https://github.com/philferriere/cocoapi.git#egg=pycocotools&subdirectory=PythonAPI
  Cloning https://github.com/philferriere/cocoapi.git to /tmp/pip-install-4t59ff3c/pycocotools
Building wheels for collected packages: pycocotools
  Running setup.py bdist_wheel for pycocotools ... done
  Stored in directory: /tmp/pip-ephem-wheel-cache-_umvwmpn/wheels/69/2b/12/2fa959e49f73d26cff202c2f4e5079096c9c57c8a8509fd75c
Successfully built pycocotools
ipykernel 4.8.2 has requirement ipython>=4.0.0, but you'll have ipython 2.4.1 which is incompatible.
ipywidgets 7.2.0 has requirement ipython>=4.0.0; python_version >= "3.3", but you'll have ipython 2.4.1 which is incompatible.
Installing collected packages: pycocotools
```

**Comment by alicest9** [comment]
Prepending `sudo -H`:
```bash
sudo -H pip install "git+https://github.com/philferriere/cocoapi.git#egg=pycocotools&subdirectory=PythonAPI"
```
Results in:
```
Collecting pycocotools from git+https://github.com/philferriere/cocoapi.git#egg=pycocotools&subdirectory=PythonAPI
  Cloning https://github.com/philferriere/cocoapi.git to /tmp/pip-install-_izpiaqz/pycocotools
Building wheels for collected packages: pycocotools
  Running setup.py bdist_wheel for pycocotools ... done
  Stored in directory: /tmp/pip-ephem-wheel-cache-3xhp6ij5/wheels/69/2b/12/2fa959e49f73d26cff202c2f4e5079096c9c57c8a8509fd75c
Successfully built pycocotools
ipywidgets 7.2.0 has requirement ipython>=4.0.0; python_version >= "3.3", but you'll have ipython 2.4.1 which is incompatible.
ipykernel 4.8.2 has requirement ipython>=4.0.0, but you'll have ipython 2.4.1 which is incompatible.
Installing collected packages: pycocotools
Successfully installed pycocotools-2.0
You are using pip version 10.0.1, however version 19.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```

But:
```python
>>> import pycocotools
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named pycocotools
```

**Comment by alicest9** [comment]
Apparently solved via:
```bash
sudo apt remove ipython3
sudo -H pip3 install --upgrade six==1.10.0
sudo -H pip3 install --upgrade prompt-toolkit==1.0.15
sudo -H pip3 install --upgrade ipython==4.0.0
sudo -H pip install "git+https://github.com/philferriere/cocoapi.git#egg=pycocotools&subdirectory=PythonAPI"
```

**Comment by alicest9** [comment]
On titan, running:
```bash


teo@teo-titan:~/repos/traineeship/python/Mask_RCNN/samples/coco (master % u+2)$ python3 coco.py train --dataset=/home/teo/repos/traineeship/python/Mask_RCNN/samples/coco  --model=coco

```
results in:
```
Traceback (most recent call last):
  File "coco.py", line 55, in <module>
    from mrcnn.config import Config
ImportError: No module named 'mrcnn'
```

Find only this :  https://github.com/matterport/Mask_RCNN/issues/485
